[workspace]
members = ["dbuf-core", "dbuf-gen", "dbuf-lsp", "runtime/dbuf-rust-runtime"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
dbuf-core = { path = "./dbuf-core" }
