[package]
name = "dbuf-storage"
edition = "2021"
version.workspace = true

[dependencies]
dbuf-core = { path = "../dbuf-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.0.0"
rand = "0.8"
sled = "0.34.7"